name: singular
version: 12.04.28dev
date: 2012-04-28
description: |
    A GAP interface to Singular

authors:
    - name: Marco Costantini
    - name: Willem de Graaf
      url: https://www.science.unitn.it/~degraaf/

maintainers:
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">=4.8"

www: https://gap-packages.github.io/singular/
readme: README.md
packageinfo: https://gap-packages.github.io/singular/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/singular/releases/download/v12.04.28dev/singular-12.04.28dev.tar.gz

abstract: |
    The <span class="pkgname">singular</span> package provides an interface    from <span class="pkgname">GAP</span> to the computer algebra system    <span class="pkgname">Singular</span>.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    Interface to Singular, Groebner bases.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>CGT12</span>]   <b class='BibAuthor'>Costantini, M., de Graaf, W. and GAP Team, T.</b>,
     <i class='BibTitle'>singular, A GAP interface to Singular,
             Version 12.04.28dev</i>
     (<span class='BibYear'>2012</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/singular/">https://gap-packages.github.io/singular/</a></span>.
    </p>
    

bibtex: |
    @misc{ singular12.04.28dev,
      author =           {Costantini, M. and de Graaf, W. and GAP Team, T.},
      title =            {{singular}, A GAP interface to Singular, {V}ersion 12.04.28dev},
      month =            {Apr},
      year =             {2012},
      note =             {GAP package},
      howpublished =     {\href {https://gap-packages.github.io/singular/} {\texttt{https://gap-packages.github.io/}\discretionary {}{}{}\texttt{singular/}}},
      keywords =         {Interface to Singular; Groebner bases},
      printedkey =       {CGT12}
    }

