name: singular
version: "2023.02.09"
license: "GPL-2.0-or-later"
date: 2023-02-09
description: |
    A GAP interface to Singular

authors:
    - name: Marco Costantini
    - name: Willem Adriaan de Graaf
      url: https://www.science.unitn.it/~degraaf/

maintainers:
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">=4.8"

www: https://gap-packages.github.io/singular/
readme: README.md
packageinfo: https://gap-packages.github.io/singular/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/singular/releases/download/v2023.02.09/singular-2023.02.09.tar.gz

abstract: |
    The <span class="pkgname">singular</span> package provides an interface    from <span class="pkgname">GAP</span> to the computer algebra system    <span class="pkgname">Singular</span>.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    Interface to Singular, Groebner bases.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>CGT23</span>]   <b class='BibAuthor'>Costantini, M., de Graaf, W. A. and GAP Team, T.</b>,
     <i class='BibTitle'>singular, A GAP interface to Singular,
             Version 2023.02.09</i>
     (<span class='BibYear'>2023</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/singular/">https://gap-packages.github.io/singular/</a></span>.
    </p>
    

bibtex: |
    @misc{ singular2023.02.09,
      author =           {Costantini, M. and de Graaf, W. A. and GAP Team, T.},
      title =            {{singular},  A  GAP  interface  to Singular, {V}ersion
                          2023.02.09},
      month =            {Feb},
      year =             {2023},
      note =             {GAP package},
      howpublished =     {\href       {https://gap-packages.github.io/singular/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{singular/}}},
      keywords =         {Interface to Singular; Groebner bases},
      printedkey =       {CGT23}
    }

